
services:
  - type: web
    name: rag-assistant
    runtime: python
    plan: starter

    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app/main.py --server.port=$PORT --server.address=0.0.0.0
    healthCheckPath: /

    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      
      # API keys and environment variables (set manually in the Render dashboard)
      - key: TOGETHER_API_KEY
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_ENVIRONMENT
        sync: false
      - key: PINECONE_INDEX_NAME
        sync: false